import type { CareClusterLandingConfig } from './types'
import { CARE_PATH } from './paths'

const TRUST_DEFAULT = [
  { num: '10,000+', label: 'Families served across India' },
  { num: '16+', label: 'Bangalore localities covered' },
  { num: '2 yrs+', label: 'Minimum experience required' },
  { num: '100%', label: 'Verified, screened, briefed' },
] as const

/** Re-export for view if we ever vary per cluster */
export const CLUSTER_TRUST_STRIP = TRUST_DEFAULT

export const CLUSTER_LANDING_CONFIGS = {
  homeHealthcare: {
    breadcrumbCurrent: 'Home Healthcare Services',
    eyebrow: 'Bangalore · In-home medical care',
    hero: {
      line1: 'Hospital-grade care.',
      line2Before: 'Brought home, ',
      line2Accent: 'beautifully.',
    },
    heroChips: [
      { icon: 'check', title: 'Verified professionals', sub: 'Aadhaar + credential checks', grad: 'from-sky-500 to-primary-500' },
      { icon: 'heart', title: 'Doctor-aligned', sub: 'Care plan continuity', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'clock', title: 'Rapid response', sub: 'Often within hours', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'One service.',
      titleLine2Lead: 'One team.',
      titleLine2Muted: 'One coordinated outcome.',
      lede: 'Most providers force a choice — a nurse or a caretaker. Home Healthcare is the integrated service for patients who genuinely need both, working in step.',
      featured: {
        tag: 'This page · Recommended',
        title: 'Home Healthcare',
        description: 'For patients who need medical procedures and daily care, working as one coordinated team.',
        bullets: [
          'Nurse + caretaker placement',
          'Doctor-aligned care plan',
          'Wound, vitals, medication',
          'Hygiene, mobility, feeding',
          'Family updates throughout',
        ],
        ctaLabel: 'Start a placement',
      },
      altLeft: {
        tag: 'Medical only',
        title: 'Home Nursing',
        description: 'Procedural medical care: wound dressing, IV, catheter, vital monitoring.',
        href: CARE_PATH.homeNursing,
      },
      altRight: {
        tag: 'Daily care only',
        title: 'Caretakers',
        description: 'Hygiene, feeding, mobility support, and companionship for daily living.',
        href: CARE_PATH.caretaker,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Care that is medically informed',
      titleLine2Muted: 'and humanly held.',
      pillars: [
        { num: '01', title: 'Medical and daily care, one coordinated service.', description: 'One team manages nursing tasks and personal care together — no juggling vendors, no gaps in handoffs.', span: 3 },
        { num: '02', title: 'Responsive support after hospital discharge.', description: "When discharge plans change, we move quickly to match the right professional to the patient's situation.", span: 3, heartbeat: true },
        { num: '03', title: 'Condition-specific matching.', description: 'Cardiac, neuro, oncology — we match experience to diagnosis.', span: 2 },
        { num: '04', title: 'Doctor-aligned plans.', description: "The team is briefed on your doctor's instructions and follows them.", span: 2 },
        { num: '05', title: 'Ongoing follow-through.', description: 'We check in after the first week, and stay reachable throughout.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'Care arrangements,',
      titleLine2Muted: 'shaped to the situation.',
      lede: "We don't sell packages. We design care around medical complexity and the rhythm of your home.",
      scrollHint: 'Day · night · full-time · live-in arrangements',
    },
    serviceCards: [
      { tag: 'Recovery', title: 'Post-surgery recovery', body: 'Cardiac, orthopaedic, abdominal — medical attention paired with daily care.', tone: 'c1' },
      { tag: 'Stroke + Paralysis', title: 'Post-stroke and paralysis care', body: 'Mobility support, transfer assistance, and continued therapy follow-through.', tone: 'c2' },
      { tag: 'Chronic care', title: 'Long-term illness management', body: 'Diabetes, COPD, kidney conditions — with regular monitoring and reporting.', tone: 'c3' },
      { tag: 'ICU transition', title: 'ICU discharge home transition', body: 'Bridging hospital-grade attention with the comforts of home.', tone: 'c4' },
      { tag: 'Neurology', title: "Dementia and Alzheimer's", body: 'Continuous, gentle supervision with familiarity and patience.', tone: 'c5' },
      { tag: 'Palliative', title: 'Cancer palliative care', body: 'Medical comfort and daily support, delivered with dignity.', tone: 'c6' },
    ],
    conditionsIntro: {
      eyebrow: 'Conditions we handle',
      titleLine1: 'A range of situations.',
      titleLine2Muted: 'One steady standard.',
      lede: 'Our professionals have managed each of these in Bangalore homes. For complex or rare cases, speak with our team for a personalised assessment.',
    },
    conditions: [
      'Post-cardiac surgery (bypass, angioplasty)',
      'Stroke recovery and paralysis care',
      'Diabetes management and monitoring',
      'Knee replacement, hip surgery, fractures',
      'ICU discharge and post-hospital recovery',
      'Cancer care and palliative support',
      "Parkinson's and neurological conditions",
      'Bedridden care, pressure sore support',
      'COPD, asthma, breathing conditions',
      'Kidney conditions, dialysis support',
      'Post-abdominal surgery recovery',
      'General elderly mobility support',
    ],
    stories: [
      {
        quote:
          'My father had bypass surgery and came home with strict care instructions and a long list of medicines. The home healthcare professional arranged by EzyHelpers had experience in cardiac recovery. She followed all instructions carefully, kept us informed, and handled my father with patience and confidence. That support made a big difference in his recovery.',
        emphasisPhrase: 'That support made a big difference in his recovery.',
        name: 'Suresh Parthasarathy',
        location: 'Sarjapur Road, Bangalore',
        initials: 'SP',
      },
      {
        quote:
          'My mother has serious breathing issues (COPD), and we needed continuous care at home. The professional provided by EzyHelpers understood how to manage oxygen support and monitor her condition closely. She also stayed in touch with our doctor when needed. Her experience helped us handle difficult situations at home without rushing to the hospital every time.',
        emphasisPhrase: 'Her experience helped us handle difficult situations at home without rushing to the hospital every time.',
        name: 'Ananya Rao',
        location: 'Yelahanka, Bangalore',
        initials: 'AR',
      },
      {
        quote:
          "After my husband's kidney transplant, we needed very careful home care because of his sensitive condition. EzyHelpers took time to find someone with the right experience. She managed his medicines properly, followed all precautions, and kept us updated regularly. We felt confident knowing he was getting proper care at home.",
        emphasisPhrase: 'We felt confident knowing he was getting proper care at home.',
        name: 'Lalitha Iyer',
        location: 'Rajajinagar, Bangalore',
        initials: 'LI',
      },
    ],
    processIntro: {
      eyebrow: 'How it works',
      title: 'Four steps, handled with precision.',
      lede: 'From first call to first day on the job — and well beyond — every step is held by a real person on our team.',
    },
    processSteps: [
      {
        mark: 'i',
        title: 'Free consultation',
        body: "We understand the diagnosis, the doctor's instructions, the daily routines, and what the family is hoping for. We recommend the right combination of nurse and caretaker — or whether one is sufficient.",
      },
      {
        mark: 'ii',
        title: 'Coordinated shortlisting',
        body: "Suitable professionals are matched to the patient's specific situation. A cardiac patient is paired with someone experienced in cardiac recovery, not generic post-op care.",
      },
      {
        mark: 'iii',
        title: 'Interview and matching',
        body: "You review qualifications, relevant past work, and can speak with shortlisted candidates. You choose who you're most comfortable with.",
      },
      {
        mark: 'iv',
        title: 'Onboarding and ongoing support',
        body: 'The professional is briefed on the care plan and routine. We follow up after the first week and remain reachable throughout the placement.',
      },
    ],
    finalCta: {
      titleBefore: 'Start home healthcare,',
      titleGradient: 'matched to your loved one.',
      lede: 'Tell us your situation — our team typically responds within the hour on business days.',
      showPillarLink: true,
      pillarLinkLabel: '← Home care services overview',
    },
  } satisfies CareClusterLandingConfig,

  homeNursing: {
    breadcrumbCurrent: 'Home Nursing Services',
    eyebrow: 'Bangalore · Licensed home nurses',
    hero: {
      line1: 'Clinical procedures.',
      line2Before: 'Delivered at home, ',
      line2Accent: 'safely.',
    },
    heroChips: [
      { icon: 'shield', title: 'Qualified nurses', sub: 'GNM / B.Sc verification', grad: 'from-sky-500 to-primary-500' },
      { icon: 'check', title: 'Procedure-ready', sub: 'Wound, IV, catheter', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'spark', title: 'Doctor handoffs', sub: 'Clear reporting', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'Medical tasks only.',
      titleLine2Muted: 'Done by the right nurse.',
      lede: 'When your patient needs licensed procedures — not general companionship — Home Nursing places nurses trained for exactly that scope of work.',
      featured: {
        tag: 'This page · Recommended',
        title: 'Home Nursing',
        description: 'Wound care, IV therapy, catheter management, vitals, injections — performed by verified nurses at home.',
        bullets: ['Credential-checked nurses', 'Equipment & protocol discipline', 'Daily documentation', 'Family updates', 'Replacement if needed'],
        ctaLabel: 'Request a nurse',
      },
      altLeft: {
        tag: 'Medical + daily care',
        title: 'Home Healthcare',
        description: 'Combined nurse + caretaker when both medical procedures and daily support are required.',
        href: CARE_PATH.homeHealthcare,
      },
      altRight: {
        tag: 'Non-medical care',
        title: 'Caretakers',
        description: 'Hygiene, feeding, mobility, and companionship without licensed procedures.',
        href: CARE_PATH.caretaker,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Nursing that respects',
      titleLine2Muted: 'your doctor’s plan.',
      pillars: [
        { num: '01', title: 'Scope clarity from day one.', description: 'We confirm which procedures are needed so the nurse matches license and experience.', span: 3 },
        { num: '02', title: 'Fast placement when urgency matters.', description: 'Post-discharge and changing vitals — we prioritise suitable nurses for your window.', span: 3, heartbeat: true },
        { num: '03', title: 'Condition familiarity.', description: 'Cardiac, renal, post-op — shortlists reflect relevant bedside experience.', span: 2 },
        { num: '04', title: 'Transparent communication.', description: 'Plain-language updates for families, aligned with treating teams.', span: 2 },
        { num: '05', title: 'Ongoing supervision.', description: 'We stay reachable for escalations, swaps, and schedule shifts.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'Nursing scope,',
      titleLine2Muted: 'mapped to your case.',
      lede: 'From single-shift visits to extended coverage — structured around the procedures your patient requires.',
    },
    serviceCards: [
      { tag: 'Wounds', title: 'Dressing & wound care', body: 'Sterile technique, infection watch, surgeon-aligned changes.', tone: 'c1' },
      { tag: 'IV & fluids', title: 'IV therapy', body: 'Administration and monitoring per prescription.', tone: 'c2' },
      { tag: 'Catheter', title: 'Catheter care', body: 'Management and hygiene with nursing protocol.', tone: 'c3' },
      { tag: 'Vitals', title: 'Monitoring', body: 'BP, SpO₂, glucose — logged and escalated appropriately.', tone: 'c4' },
      { tag: 'Injections', title: 'Medication admin', body: 'Injections and critical oral meds per doctor orders.', tone: 'c5' },
      { tag: 'Post-op', title: 'Post-surgical nursing', body: 'Recovery monitoring after cardiac, orthopaedic, or major surgery.', tone: 'c6' },
    ],
    conditionsIntro: {
      eyebrow: 'Situations we support',
      titleLine1: 'Procedures & monitoring.',
      titleLine2Muted: 'At home.',
      lede: 'Common scenarios our Bangalore nurses cover — call us if yours is not listed.',
    },
    conditions: [
      'Post-cardiac procedure monitoring',
      'Post-transplant medication supervision',
      'Chronic wound management',
      'Diabetes insulin & glucose checks',
      'Post-orthopaedic surgery recovery',
      'Kidney care coordination at home',
      'Respiratory therapy support (per plan)',
      'Oncology symptom monitoring (non-chemo)',
      'Neuro recovery observation',
      'Bedridden pressure-area nursing',
      'Feeding tube / supplemental care (per scope)',
      'Hospital-discharge handoff care',
    ],
    stories: [
      {
        quote:
          "After my father's heart surgery, we were worried about managing his care at home. The nurse provided regular dressing, monitored his BP and oxygen levels daily, and kept us informed about his recovery. Her timely attention helped us avoid complications and made the transition from hospital to home much smoother.",
        emphasisPhrase: 'made the transition from hospital to home much smoother.',
        name: 'Family',
        location: 'Bangalore',
        initials: 'B',
      },
      {
        quote:
          'My son had a kidney transplant and needed careful care at home. The nurse managed medication timing properly, monitored his health daily, and kept us informed regularly. Six months later, his recovery has been stable.',
        emphasisPhrase: 'his recovery has been stable.',
        name: 'Parent',
        location: 'Bangalore',
        initials: 'P',
      },
      {
        quote:
          'My father had spinal surgery and needed careful movement and wound care. The nurse knew how to support him safely, managed his care properly, and explained updates clearly to us daily.',
        emphasisPhrase: 'explained updates clearly to us daily.',
        name: 'Son',
        location: 'Bangalore',
        initials: 'S',
      },
    ],
    processIntro: {
      eyebrow: 'How it works',
      title: 'Four steps. Nursing-first.',
      lede: 'We shortlist nurses whose credentials and experience match the procedures you need.',
    },
    processSteps: [
      { mark: 'i', title: 'Clinical consultation', body: 'We capture diagnosis, doctor orders, shift pattern, and equipment needs.' },
      { mark: 'ii', title: 'Nurse shortlisting', body: 'Only nurses with relevant procedure experience and valid credentials.' },
      { mark: 'iii', title: 'Interview & confirm', body: 'You meet or speak with candidates before confirmation.' },
      { mark: 'iv', title: 'Start & monitor', body: 'Handover to home, early-shift check-ins, and swap support if needed.' },
    ],
    finalCta: {
      titleBefore: 'Book home nursing',
      titleGradient: 'aligned to your prescription.',
      lede: 'Share the procedure list and schedule — we respond quickly across Bangalore.',
      showPillarLink: true,
    },
  } satisfies CareClusterLandingConfig,

  elderlyCare: {
    breadcrumbCurrent: 'Elderly Care · Bangalore',
    eyebrow: 'Bangalore · Dignity-first',
    heroLead:
      'Verified caretakers for senior citizens, dementia care, Parkinson\'s support, and live-in elderly care — matched with empathy, not just availability.',
    heroCaptions: ['Companionship', 'Daily routines', 'A calm home'],
    primaryCtaLabel: 'Find a caretaker',
    hero: {
      line1: 'Care that lets your parent age',
      line2Before: '',
      line2Accent: 'at home',
      line2After: ', on their terms.',
    },
    heroChips: [
      { icon: 'check', title: 'Verified caretakers', sub: 'Aadhaar + background', grad: 'from-rose-500 to-primary-500' },
      { icon: 'chat', title: 'Family updates', sub: 'For NRI / outstation', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'clock', title: 'Live-in or shifts', sub: 'Day · night · 24×7', grad: 'from-orange-500 to-amber-500' },
      { icon: 'heart', title: 'Replacement promise', sub: 'If fit feels wrong', grad: 'from-fuchsia-600 to-rose-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'Built for seniors.',
      titleLine2Muted: 'Not generic “help”.',
      lede: 'Elderly Care matches professionals who understand ageing, cognition, and the emotional side of losing independence.',
      featured: {
        tag: '★ Recommended',
        title: 'Elderly Care',
        description: 'Companionship, routines, medication reminders, mobility, and dignity-first support for older adults.',
        bullets: [
          'Dementia / Parkinson\'s familiarity',
          'Language match',
          'Live-in or shifts',
          'Family updates',
          'Free replacement',
        ],
        ctaLabel: 'Find elderly care',
      },
      altLeft: {
        tag: 'Medical procedures',
        title: 'Home Nursing',
        description: 'When licensed procedures — IV, wound care, catheter management — are the primary need.',
        href: CARE_PATH.homeNursing,
      },
      altRight: {
        tag: 'Recovery focus',
        title: 'Patient Care',
        description: 'Structured recovery from surgery or illness — not only age-related support.',
        href: CARE_PATH.patientCare,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Matching beyond',
      titleLine2Muted: 'availability.',
      pillars: [
        {
          num: '01',
          title: 'Consultation that listens',
          description: 'We capture routines, triggers, and how your parent prefers to be addressed.',
          span: 2,
        },
        {
          num: '02',
          title: 'Experience with cognitive change',
          description: 'Shortlists weighted toward dementia, Parkinson\'s, or frailty — as applicable.',
          span: 2,
          heartbeat: true,
        },
        {
          num: '03',
          title: 'Live-in continuity',
          description: 'Stable placements when overnight supervision matters most.',
          span: 2,
        },
        {
          num: '04',
          title: 'Family alignment',
          description: 'Updates that work for both local and remote children.',
          span: 2,
        },
        {
          num: '05',
          title: 'Replacement promise',
          description: 'If the fit feels wrong, we restart — without friction or paperwork.',
          span: 2,
        },
        {
          num: '06',
          title: 'A real human, on call',
          description: 'No bots. A coordinator who knows your parent\'s name and routine.',
          span: 2,
          spotlight: true,
        },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'Senior support, designed',
      titleLine2Muted: 'around the person.',
      lede: 'From companionship to full live-in supervision — scaled to mobility and cognition.',
      scrollHint: 'View all arrangements · Flexible options across Bangalore',
    },
    serviceCards: [
      {
        badge: 'Most requested',
        title: 'Daily companionship',
        body: 'Conversation, gentle stimulation, and routine.',
        detail: 'Day · evening · weekend shifts',
        priceBold: 'Live-in',
        priceRest: ' or hourly · Bangalore-wide',
        rating: '4.9',
        tone: 'c1',
      },
      {
        title: 'Memory-aware care',
        body: 'Patience, repetition, safety in familiar spaces.',
        detail: 'Dementia · early Alzheimer\'s · cognitive decline',
        priceBold: 'Specialised',
        priceRest: ' matching · Bangalore-wide',
        rating: '4.8',
        tone: 'c2',
      },
      {
        title: 'Mobility & medication',
        body: 'Timing-critical medication and movement assistance.',
        detail: 'Parkinson\'s · post-fall · frailty',
        priceBold: 'Trained',
        priceRest: ' caretakers · Bangalore-wide',
        rating: '4.9',
        tone: 'c3',
      },
      {
        badge: '24×7',
        title: 'Live-in supervision',
        body: 'Continuity for high fall-risk or wandering.',
        detail: 'Day & night · stays in home',
        priceBold: 'Long-term',
        priceRest: ' placements · Bangalore-wide',
        rating: '5.0',
        tone: 'c4',
      },
      {
        title: 'Meals & hydration',
        body: 'Diet-aware feeding and supervision.',
        detail: 'Diabetes · BP · soft diet · custom prep',
        priceBold: 'Cooked',
        priceRest: " per doctor's plan · Bangalore-wide",
        rating: '4.9',
        tone: 'c5',
      },
      {
        title: 'Family bridge',
        body: 'Structured updates for NRI / outstation children.',
        detail: 'Weekly reports · video check-ins · alerts',
        priceBold: 'Included',
        priceRest: ' in placement · Bangalore-wide',
        rating: '4.8',
        tone: 'c6',
      },
    ],
    conditionsIntro: {
      eyebrow: 'Situations we support',
      titleLine1: 'Ageing & chronic needs.',
      titleLine2Muted: 'Handled gently.',
      lede: 'Typical elderly-care scenarios we place for across Bangalore.',
    },
    conditions: [
      '🧠 Mild cognitive impairment & dementia',
      '🚶 Parkinson\'s mobility & medication timing',
      '🩹 Post-fall recovery supervision',
      '💊 Diabetes & hypertension routines',
      '🍲 Loneliness & meal supervision',
      '🏠 Live-in for fragile seniors',
      '🌙 Overnight supervision',
      '🤲 End-of-life comfort (non-clinical)',
      '🏥 Transition after hospital discharge',
      '🗣️ Language-specific companionship',
      '🧘 Physiotherapy coordination',
      '⏰ Medication reminder discipline',
    ],
    stories: [
      {
        quote:
          'EzyHelpers matched us with a caretaker who had worked specifically with Parkinson\'s patients. She understands the tremor cycles, knows when to assist and when to let him try independently, and speaks to him in Kannada.',
        emphasisPhrase: 'speaks to him in Kannada.',
        name: 'Rajesh K.',
        location: 'HSR Layout · Father (78)',
        initials: 'RK',
      },
      {
        quote:
          'I\'m in Singapore. Knowing my mother has someone consistent in the house — and that I get a real update every week, not a generic message — is what lets me sleep.',
        emphasisPhrase: 'is what lets me sleep.',
        name: 'Priya N.',
        location: 'NRI · Mother in Indiranagar',
        initials: 'PN',
      },
      {
        quote:
          'First placement didn\'t fit — and they didn\'t make us feel bad about asking. The replacement has been with my mother-in-law for fourteen months now. That speaks for itself.',
        emphasisPhrase: 'That speaks for itself.',
        name: 'Anita S.',
        location: 'Whitefield · Mother-in-law (82)',
        initials: 'AS',
      },
    ],
    processIntro: {
      eyebrow: 'How it works',
      title: 'Four steps. Human-first.',
      lede: 'We optimise for dignity, safety, and family peace of mind.',
    },
    processSteps: [
      {
        mark: 'i',
        title: 'Understanding your parent',
        body: 'Health, habits, language, and what “good days” look like for them.',
      },
      {
        mark: 'ii',
        title: 'Shortlist with intent',
        body: 'Caretakers with relevant elderly experience — not whoever happens to be free.',
      },
      {
        mark: 'iii',
        title: 'Meet & choose',
        body: 'You decide who feels right in the home. The fit matters as much as the resume.',
      },
      {
        mark: 'iv',
        title: 'Settling in',
        body: 'Early follow-ups and adjustments as routines stabilise into something steady.',
      },
    ],
    finalCta: {
      titleBefore: 'Arrange elderly care that',
      titleGradient: 'feels like family.',
      lede: 'Tell us about your parent — their name, their routine, what would help most. We respond quickly.',
      showPillarLink: true,
    },
  } satisfies CareClusterLandingConfig,

  caretaker: {
    breadcrumbCurrent: 'Caretaker Services',
    eyebrow: 'Bangalore · Full-time & live-in caretakers',
    hero: {
      line1: 'Daily care, covered.',
      line2Before: 'Matched with ',
      line2Accent: 'precision.',
    },
    heroChips: [
      { icon: 'check', title: 'Verified', sub: 'ID & references', grad: 'from-sky-500 to-primary-500' },
      { icon: 'heart', title: 'Personal care', sub: 'Hygiene & feeding', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'clock', title: 'Flexible shifts', sub: 'Day, night, live-in', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'Caretaker ≠ nurse.',
      titleLine2Muted: 'Both have a place.',
      lede: 'Caretakers handle non-medical daily living. When procedures need a license, we layer nursing or redirect you.',
      featured: {
        tag: 'This page · Recommended',
        title: 'Caretaker',
        description: 'Personal care, medication reminders, mobility, meals, and companionship — without licensed clinical tasks.',
        bullets: ['Hygiene & grooming', 'Feeding assistance', 'Transfers & mobility', 'Medication reminders', 'Replacements'],
        ctaLabel: 'Find a caretaker',
      },
      altLeft: {
        tag: 'Senior-focused',
        title: 'Elderly Care',
        description: 'When the primary need is ageing, cognition, and dignity-first routines.',
        href: CARE_PATH.elderlyCare,
      },
      altRight: {
        tag: 'Medical procedures',
        title: 'Home Nursing',
        description: 'Wound, IV, catheter — requires a licensed nurse.',
        href: CARE_PATH.homeNursing,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Fit over',
      titleLine2Muted: 'speed.',
      pillars: [
        { num: '01', title: 'Household chemistry.', description: 'We optimise for temperament and communication style — not just CVs.', span: 3 },
        { num: '02', title: 'Same-day when possible.', description: 'Urgent discharges — we push for fastest safe placement.', span: 3, heartbeat: true },
        { num: '03', title: 'Experience signals.', description: 'Cardiac recovery, dementia, bedridden — matched deliberately.', span: 2 },
        { num: '04', title: 'Replacement guarantee.', description: 'If comfort or skill is off, we re-shortlist.', span: 2 },
        { num: '05', title: 'Ongoing access.', description: 'Our team stays in reach after start date.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'Caretaking roles,',
      titleLine2Muted: 'clearly scoped.',
      lede: 'Choose the level of physical assistance and hours your patient needs.',
    },
    serviceCards: [
      { tag: 'Live-in', title: 'Full-time live-in', body: 'Continuity for high-dependency patients.', tone: 'c1' },
      { tag: 'Day', title: 'Day-shift care', body: 'Coverage while family is at work.', tone: 'c2' },
      { tag: 'Night', title: 'Night supervision', body: 'Safety for fall-risk or wandering.', tone: 'c3' },
      { tag: 'Post-op', title: 'Non-clinical recovery', body: 'Mobility & meals after surgery — alongside nursing if needed.', tone: 'c4' },
      { tag: 'Bedridden', title: 'Bedside routines', body: 'Turning, hygiene, feeding support.', tone: 'c5' },
      { tag: 'Companionship', title: 'Social engagement', body: 'Conversation and activity for isolated patients.', tone: 'c6' },
    ],
    conditionsIntro: {
      eyebrow: 'Use cases',
      titleLine1: 'Who caretakers help.',
      titleLine2Muted: 'Every day.',
      lede: 'Common situations — call us if yours is blended or unclear.',
    },
    conditions: [
      'Post-surgical non-clinical recovery',
      'Elderly frailty & supervision',
      'Dementia companionship',
      'Bedridden hygiene & feeding',
      'Parkinson’s mobility assist',
      'Stroke recovery support (non-procedure)',
      'Single-shift relief for family caregivers',
      'Couple care in one home',
      'Travel / NRI parent coverage',
      'Meal preparation for patient only',
      'Medication reminder (non-injection)',
      'Live-in for chronic illness',
    ],
    stories: [
      {
        quote:
          'I called EzyHelpers in the morning, and by afternoon, a verified caretaker was at his home in Koramangala. She had specific experience with post-cardiac patients, managed his medications precisely, and called me every evening with an update.',
        emphasisPhrase: 'called me every evening with an update.',
        name: 'Son',
        location: 'Koramangala, Bangalore',
        initials: 'S',
      },
      {
        quote:
          'EzyHelpers matched us with a caretaker who had worked specifically with dementia patients. She knows how to handle confused moments, keeps a daily log, and speaks to my mother in Kannada.',
        emphasisPhrase: 'speaks to my mother in Kannada.',
        name: 'Daughter',
        location: 'Malleshwaram, Bangalore',
        initials: 'D',
      },
      {
        quote:
          'EzyHelpers was thorough about matching someone with spinal care experience. There was one early adjustment needed, and EzyHelpers resolved it the same day we raised it.',
        emphasisPhrase: 'resolved it the same day we raised it.',
        name: 'Husband',
        location: 'Bangalore',
        initials: 'H',
      },
    ],
    processIntro: { eyebrow: 'How it works', title: 'Placement with clarity.', lede: 'Shortlists you can trust — then interviews you control.' },
    processSteps: [
      { mark: 'i', title: 'Needs call', body: 'Medical context (non-clinical), mobility, schedule, languages.' },
      { mark: 'ii', title: 'Shortlist', body: '2–3 caretakers with relevant experience.' },
      { mark: 'iii', title: 'Meet', body: 'Interview before commitment.' },
      { mark: 'iv', title: 'Start + follow-up', body: 'Week-one check-in and ongoing support.' },
    ],
    finalCta: { titleBefore: 'Hire a caretaker', titleGradient: 'you can trust in your home.', lede: 'Share the routine — we shortlist fast.', showPillarLink: true },
  } satisfies CareClusterLandingConfig,

  patientCare: {
    breadcrumbCurrent: 'Patient Care Services',
    eyebrow: 'Bangalore · Recovery & illness at home',
    hero: {
      line1: 'Recovery, supervised.',
      line2Before: 'At home, ',
      line2Accent: 'properly.',
    },
    heroChips: [
      { icon: 'check', title: 'Recovery-focused', sub: 'Post-surgery & illness', grad: 'from-sky-500 to-primary-500' },
      { icon: 'heart', title: 'Daily routines', sub: 'Hygiene to mobility', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'spark', title: 'Doctor-aware', sub: 'Instructions followed', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'Patient care targets',
      titleLine2Muted: 'recovery — not just age.',
      lede: 'When the situation is about getting better from a condition or surgery, Patient Care aligns caretaking to that goal.',
      featured: {
        tag: 'This page · Recommended',
        title: 'Patient Care',
        description: 'Structured support for patients recovering from surgery or managing active medical conditions at home.',
        bullets: ['Goal-oriented routines', 'Mobility assistance', 'Medication reminders', 'Vitals observation & reporting', 'Family updates'],
        ctaLabel: 'Start patient care',
      },
      altLeft: {
        tag: 'Medical procedures',
        title: 'Home Healthcare',
        description: 'When licensed nursing tasks must combine with daily care under one plan.',
        href: CARE_PATH.homeHealthcare,
      },
      altRight: {
        tag: 'Daily non-medical',
        title: 'Caretaker',
        description: 'Broad personal care without a recovery-specific framing.',
        href: CARE_PATH.caretaker,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Recovery-minded',
      titleLine2Muted: 'matching.',
      pillars: [
        { num: '01', title: 'Clinical context captured.', description: 'Discharge notes, restrictions, and red flags — upfront.', span: 3 },
        { num: '02', title: 'Experience that matches the diagnosis.', description: 'Orthopaedic, cardiac, neuro — different recovery paths.', span: 3, heartbeat: true },
        { num: '03', title: 'Structured communication.', description: 'Updates that help families coordinate with doctors.', span: 2 },
        { num: '04', title: 'Escalation judgment.', description: 'Knowing when to call the family or physician.', span: 2 },
        { num: '05', title: 'Replacement safety net.', description: 'If recovery needs change, we adjust.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'Support through',
      titleLine2Muted: 'the arc of recovery.',
      lede: 'Shift patterns and intensity scaled to how your patient is progressing.',
    },
    serviceCards: [
      { tag: 'Post-op', title: 'Surgical recovery', body: 'Mobility, dressing, and routine per surgeon guidance.', tone: 'c1' },
      { tag: 'Neuro', title: 'Stroke / neuro recovery', body: 'Safe transfers and adherence to therapy homework.', tone: 'c2' },
      { tag: 'Cardiac', title: 'Cardiac rehab phase', body: 'Activity pacing and symptom awareness.', tone: 'c3' },
      { tag: 'Oncology', title: 'Illness weakness', body: 'Comfort and nutrition during treatment cycles.', tone: 'c4' },
      { tag: 'CP', title: 'Complex needs children', body: 'Routine care with patience and precision.', tone: 'c5' },
      { tag: 'Multi-morbid', title: 'Several conditions', body: 'Coordinated daily priorities.', tone: 'c6' },
    ],
    conditionsIntro: {
      eyebrow: 'Situations',
      titleLine1: 'Recovery & stability.',
      titleLine2Muted: 'At home.',
      lede: 'Examples — ask us about yours.',
    },
    conditions: [
      'Post-spine surgery mobility',
      'Post-cardiac procedure weakness',
      'Neuro recovery assistance',
      'Post-infection rebuilding strength',
      'Long covid–style fatigue management',
      'Diabetes + wound observation (non-nurse)',
      'Cancer treatment weakness',
      'Paediatric disability daily routines',
      'Multi-organ frailty coordination',
      'Fall-risk supervision post-fracture',
      'Medication routine rebuilding',
      'Family caregiver burnout relief',
    ],
    stories: [
      {
        quote:
          'The caretaker had prior experience and supported him safely during recovery. His confidence improved, and recovery was smoother than expected.',
        emphasisPhrase: 'smoother than expected.',
        name: 'Family',
        location: 'Bangalore',
        initials: 'F',
      },
      {
        quote:
          'The caretaker understood her routine, followed her exercises correctly, and treated her with patience and respect. It made a big difference to our daily life.',
        emphasisPhrase: 'made a big difference to our daily life.',
        name: 'Parent',
        location: 'Bangalore',
        initials: 'P',
      },
      {
        quote:
          'The caretaker managed her daily routine, diet, and care responsibly. She even alerted us early about a health change, which helped avoid complications.',
        emphasisPhrase: 'helped avoid complications.',
        name: 'Family',
        location: 'Bangalore',
        initials: 'F',
      },
    ],
    processIntro: { eyebrow: 'How it works', title: 'Structured placement.', lede: 'Match recovery stage to the right professional.' },
    processSteps: [
      { mark: 'i', title: 'Clinical snapshot', body: 'We capture restrictions, goals, and family availability.' },
      { mark: 'ii', title: 'Shortlist', body: 'Caretakers with relevant recovery experience.' },
      { mark: 'iii', title: 'Interview', body: 'Choose who fits the patient’s temperament.' },
      { mark: 'iv', title: 'Progress checks', body: 'Adjust hours or skills as recovery advances.' },
    ],
    finalCta: { titleBefore: 'Start patient care', titleGradient: 'built around recovery.', lede: 'Describe the condition and discharge notes — we respond quickly.', showPillarLink: true },
  } satisfies CareClusterLandingConfig,

  homeAttendant: {
    breadcrumbCurrent: 'Home Attendant Services',
    eyebrow: 'Bangalore · Shift-based attendants',
    hero: {
      line1: 'Reliable shifts.',
      line2Before: 'For daily support ',
      line2Accent: 'at home.',
    },
    heroChips: [
      { icon: 'clock', title: 'Day / night', sub: 'Coverage you choose', grad: 'from-sky-500 to-primary-500' },
      { icon: 'check', title: 'Trained', sub: 'Safe transfers', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'heart', title: 'Routines', sub: 'Hygiene & meals', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'Attendants for',
      titleLine2Muted: 'routine living.',
      lede: 'Flexible attendant coverage when the patient is not high-dependency trained handling — but still needs consistent help.',
      featured: {
        tag: 'This page · Recommended',
        title: 'Home Attendant',
        description: 'Shift-based support for bathing, feeding, mobility, and companionship — structured around your hours.',
        bullets: ['12h / 24h patterns', 'Safe movement basics', 'Medication reminders', 'Hygiene discipline', 'Handovers between shifts'],
        ctaLabel: 'Book attendant shifts',
      },
      altLeft: {
        tag: 'High dependency',
        title: 'Trained Attendant',
        description: 'Bedridden, spinal, neurological — skilled patient handling.',
        href: CARE_PATH.trainedAttendant,
      },
      altRight: {
        tag: 'Licensed tasks',
        title: 'Home Nursing',
        description: 'When invasive procedures are required.',
        href: CARE_PATH.homeNursing,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Shift clarity',
      titleLine2Muted: '& continuity.',
      pillars: [
        { num: '01', title: 'Schedule-first matching.', description: 'Night vs day — we don’t mix profiles casually.', span: 3 },
        { num: '02', title: 'Male / female options.', description: 'When preference matters for comfort.', span: 3, heartbeat: true },
        { num: '03', title: 'Handover discipline.', description: 'Notes between day and night attendants.', span: 2 },
        { num: '04', title: 'Replacement pool.', description: 'Illness or exit — we backfill.', span: 2 },
        { num: '05', title: 'Bangalore coverage.', description: 'Broad locality placement attempts.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'Coverage patterns',
      titleLine2Muted: 'that fit the home.',
      lede: 'Hour blocks and live-in patterns — tailored to your patient.',
    },
    serviceCards: [
      { tag: 'Day', title: 'Day attendant', body: 'Activities, meals, hygiene during daylight hours.', tone: 'c1' },
      { tag: 'Night', title: 'Night attendant', body: 'Supervision and toileting overnight.', tone: 'c2' },
      { tag: '12h', title: '12-hour blocks', body: 'Predictable coverage for working families.', tone: 'c3' },
      { tag: 'Live-in', title: 'Full-time live-in', body: 'When continuity beats rotation.', tone: 'c4' },
      { tag: 'Couple', title: 'Two-shift rotation', body: 'Balanced energy for intense weeks.', tone: 'c5' },
      { tag: 'Relief', title: 'Family relief weeks', body: 'Coverage while relatives travel.', tone: 'c6' },
    ],
    conditionsIntro: {
      eyebrow: 'Good fit when',
      titleLine1: 'Routine help',
      titleLine2Muted: 'is the gap.',
      lede: 'Typical attendant scenarios — escalate to Trained Attendant if handling is specialized.',
    },
    conditions: [
      'Elderly supervision & meals',
      'Post-op mobility (non-complex)',
      'Diabetes meal discipline',
      'Parkinson’s night supervision',
      'Single-room patient coverage',
      'Bedside feeding assistance',
      'Toileting & hygiene routines',
      'Day coverage while children work',
      'Temporary family absence',
      'Orthopaedic recovery walking assist',
      'Companionship + light chores for patient',
      'Transition after hospital discharge',
    ],
    stories: [
      {
        quote:
          'The home attendant EzyHelpers placed handles everything from repositioning her safely every two hours to managing her meals and hygiene with complete dignity.',
        emphasisPhrase: 'with complete dignity.',
        name: 'Granddaughter',
        location: 'Bangalore',
        initials: 'G',
      },
      {
        quote:
          'The home attendant EzyHelpers sent had done this kind of orthopaedic recovery work before. He knew exactly how to encourage my father without pushing too hard and had him walking confidently within six weeks.',
        emphasisPhrase: 'walking confidently within six weeks.',
        name: 'Son',
        location: 'Bangalore',
        initials: 'S',
      },
      {
        quote:
          'EzyHelpers placed a male attendant who handles the nighttime mobility assistance calmly and safely. He has prevented two falls and keeps detailed notes for the day attendant.',
        emphasisPhrase: 'prevented two falls',
        name: 'Wife',
        location: 'Bangalore',
        initials: 'W',
      },
    ],
    processIntro: { eyebrow: 'How it works', title: 'Shift placement.', lede: 'We optimise for hours and gender preference first.' },
    processSteps: [
      { mark: 'i', title: 'Schedule consult', body: 'Hours, gender preference, languages, tasks.' },
      { mark: 'ii', title: 'Shortlist attendants', body: 'Experience relevant to mobility level.' },
      { mark: 'iii', title: 'Trial interaction', body: 'Meet before locking shifts.' },
      { mark: 'iv', title: 'Rotation plan', body: 'Handovers and escalation paths defined.' },
    ],
    finalCta: { titleBefore: 'Book attendant shifts', titleGradient: 'that actually show up.', lede: 'Tell us your coverage gap — we respond quickly.', showPillarLink: true },
  } satisfies CareClusterLandingConfig,

  trainedAttendant: {
    breadcrumbCurrent: 'Trained Attendant Services',
    eyebrow: 'Bangalore · High-dependency handling',
    hero: {
      line1: 'Skilled handling.',
      line2Before: 'For the most ',
      line2Accent: 'vulnerable.',
    },
    heroChips: [
      { icon: 'shield', title: 'Transfer training', sub: 'Spinal & bedridden', grad: 'from-sky-500 to-primary-500' },
      { icon: 'check', title: 'Pressure care', sub: 'Turning discipline', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'heart', title: 'Calm presence', sub: 'Patient dignity first', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'More than an attendant.',
      titleLine2Muted: 'Not yet a nurse.',
      lede: 'Trained attendants specialise in safe patient movement and bed-bound routines — without performing licensed nursing procedures.',
      featured: {
        tag: 'This page · Recommended',
        title: 'Trained Attendant',
        description: 'Bedridden, post-spinal, neurological — skilled physical handling, repositioning, and prevention-focused routines.',
        bullets: ['Safe transfers', 'Pressure-area discipline', 'Equipment familiarity', 'Family coaching', 'Night coverage'],
        ctaLabel: 'Request trained help',
      },
      altLeft: {
        tag: 'Routine shifts',
        title: 'Home Attendant',
        description: 'When dependency is moderate and handling is standard.',
        href: CARE_PATH.homeAttendant,
      },
      altRight: {
        tag: 'Medical + daily',
        title: 'Home Healthcare',
        description: 'Licensed procedures plus daily care in one service.',
        href: CARE_PATH.homeHealthcare,
      },
    },
    why: {
      eyebrow: 'Why families choose us',
      titleLine1: 'Safety-led',
      titleLine2Muted: 'shortlists.',
      pillars: [
        { num: '01', title: 'Physical competency tests.', description: 'We screen handling skill — not just paperwork.', span: 3 },
        { num: '02', title: 'Neuro & spinal familiarity.', description: 'Experience with bedridden and partial paralysis.', span: 3, heartbeat: true },
        { num: '03', title: 'Pressure prevention mindset.', description: 'Turning schedules and skin checks.', span: 2 },
        { num: '04', title: 'Equipment coordination.', description: 'Hoists, air mattresses — comfort with setup.', span: 2 },
        { num: '05', title: 'Escalation literacy.', description: 'Knowing when a nurse or ER is required.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'What we provide',
      titleLine1: 'High-dependency',
      titleLine2Muted: 'home support.',
      lede: 'Extended shifts for patients who cannot be left without skilled assistance.',
    },
    serviceCards: [
      { tag: 'Spinal', title: 'Post-spinal precautions', body: 'Movement rules from surgeon — followed strictly.', tone: 'c1' },
      { tag: 'Neuro', title: 'Neurological weakness', body: 'Transfers with patience and technique.', tone: 'c2' },
      { tag: 'Bedridden', title: 'Full bed care', body: 'Hygiene, feeding, positioning.', tone: 'c3' },
      { tag: 'Night', title: 'Night trained attendant', body: 'Fall prevention overnight.', tone: 'c4' },
      { tag: 'Bariatric', title: 'Heavy transfers', body: 'Team-disciplined approaches where needed.', tone: 'c5' },
      { tag: 'Palliative', title: 'Comfort positioning', body: 'Gentle turns and dignity.', tone: 'c6' },
    ],
    conditionsIntro: {
      eyebrow: 'High-dependency cases',
      titleLine1: 'When handling skill',
      titleLine2Muted: 'matters most.',
      lede: 'If your patient is medically complex but does not need IV/wound nursing all day — trained attendants bridge the gap.',
    },
    conditions: [
      'Post-spinal surgery immobility',
      'Complete bedridden care',
      'Advanced Parkinson’s falls risk',
      'MS / ALS mobility support',
      'Severe stroke hemiplegia',
      'Pressure sore prevention focus',
      'Post-ICU weakness (non-vent)',
      'Tracheostomy adjacent care (non-suction scope)',
      'Two-person transfer situations',
      'Night confusion & wandering risk',
      'Severe arthritis mobility',
      'Post-amputation balance training assist',
      'Family unable to lift safely',
    ],
    stories: [
      {
        quote:
          'EzyHelpers sent a trained attendant who had worked with similar patients before. He helped my father move safely, followed all instructions carefully, and stayed very calm throughout the recovery.',
        emphasisPhrase: 'stayed very calm throughout the recovery.',
        name: 'Son',
        location: 'Bangalore',
        initials: 'S',
      },
      {
        quote:
          'The attendant EzyHelpers provided understands his condition very well. He helps him get ready in the morning, manages his daily needs with respect, and even understands his signals without him having to say much.',
        emphasisPhrase: 'without him having to say much.',
        name: 'Sibling',
        location: 'Bangalore',
        initials: 'S',
      },
      {
        quote:
          'The attendant assigned by EzyHelpers followed all the doctor\'s instructions, helped with proper positioning, and made sure she stayed comfortable throughout the day.',
        emphasisPhrase: 'comfortable throughout the day.',
        name: 'Husband',
        location: 'Bangalore',
        initials: 'H',
      },
    ],
    processIntro: { eyebrow: 'How it works', title: 'Safety-first placement.', lede: 'We verify handling experience before names reach you.' },
    processSteps: [
      { mark: 'i', title: 'Dependency assessment', body: 'Transfers, cognition, equipment — documented.' },
      { mark: 'ii', title: 'Skill-matched shortlist', body: 'Only attendants with relevant heavy-care history.' },
      { mark: 'iii', title: 'Family observation', body: 'Trial handling expectations before confirm.' },
      { mark: 'iv', title: 'Supervised start', body: 'Early-shift reviews and adjustments.' },
    ],
    finalCta: { titleBefore: 'Book a trained attendant', titleGradient: 'for fragile patients.', lede: 'Describe mobility level — we prioritise safe matches.', showPillarLink: true },
  } satisfies CareClusterLandingConfig,

  pillar: {
    breadcrumbCurrent: 'Care Services',
    eyebrow: 'Bangalore · One starting point',
    hero: {
      line1: 'Every kind of care.',
      line2Before: 'One platform. ',
      line2Accent: 'One match.',
    },
    heroChips: [
      { icon: 'check', title: 'Verified network', sub: 'ID & background', grad: 'from-sky-500 to-primary-500' },
      { icon: 'heart', title: 'Human matching', sub: 'Not random', grad: 'from-teal-500 to-emerald-500' },
      { icon: 'clock', title: 'Rapid response', sub: 'Often same-day', grad: 'from-rose-500 to-amber-500' },
    ],
    difference: {
      eyebrow: 'The difference',
      titleLine1: 'We don’t place',
      titleLine2Muted: 'whoever is free.',
      lede: 'Most agencies optimise for speed. EzyHelpers optimises for fit — condition experience, communication, and your family’s rhythm.',
      featured: {
        tag: 'Start here',
        title: 'Home Care Platform',
        description: 'Nurses, caretakers, attendants — we route you to the right service line and shortlist professionals matched to the patient.',
        bullets: ['Consultation-first', '2–3 strong shortlists', 'Interview before hire', 'Verification stack', 'Free replacement'],
        ctaLabel: 'Talk to our team',
      },
      altLeft: {
        tag: 'Medical + daily',
        title: 'Home Healthcare',
        description: 'Coordinated nurse + caretaker when both clinical and daily needs apply.',
        href: CARE_PATH.homeHealthcare,
      },
      altRight: {
        tag: 'Procedures only',
        title: 'Home Nursing',
        description: 'Licensed wound, IV, catheter, vitals — when that’s the sole gap.',
        href: CARE_PATH.homeNursing,
      },
    },
    why: {
      eyebrow: 'Why Bangalore trusts us',
      titleLine1: 'Matching that goes beyond',
      titleLine2Muted: 'postcode.',
      pillars: [
        { num: '01', title: 'Consultation over guessing.', description: 'We learn condition, language, schedule, and temperament before shortlisting.', span: 3 },
        { num: '02', title: 'Verified + relevant experience.', description: 'ID checks plus condition-specific track record.', span: 3, heartbeat: true },
        { num: '03', title: 'Same-day when possible.', description: 'If a suitable professional exists — we move fast.', span: 2 },
        { num: '04', title: 'After placement support.', description: 'Follow-ups and swaps until the fit feels right.', span: 2 },
        { num: '05', title: 'City-wide coverage.', description: 'Broad Bangalore locality attempts.', span: 2 },
      ],
    },
    servicesIntro: {
      eyebrow: 'Explore services',
      titleLine1: 'Pick your lane —',
      titleLine2Muted: 'or we’ll guide you.',
      lede: 'Seven specialised Bangalore pages. Each opens with the same placement promise.',
    },
    serviceCards: [
      { tag: 'Integrated', title: 'Home Healthcare', body: 'Medical + daily care coordinated.', tone: 'c1' },
      { tag: 'Clinical', title: 'Home Nursing', body: 'Licensed procedures at home.', tone: 'c2' },
      { tag: 'Seniors', title: 'Elderly Care', body: 'Dignity-first ageing support.', tone: 'c3' },
      { tag: 'Daily', title: 'Caretaker', body: 'Personal care & companionship.', tone: 'c4' },
      { tag: 'Recovery', title: 'Patient Care', body: 'Illness & surgery recovery focus.', tone: 'c5' },
      { tag: 'Shifts', title: 'Home Attendant', body: 'Flexible attendant coverage.', tone: 'c6' },
      { tag: 'High dependency', title: 'Trained Attendant', body: 'Skilled movement & bed care.', tone: 'c1' },
    ],
    conditionsIntro: {
      eyebrow: 'Conditions & scenarios',
      titleLine1: 'Broad experience.',
      titleLine2Muted: 'One intake.',
      lede: 'From cardiac recovery to dementia — we’ve placed across these and more.',
    },
    conditions: [
      'Post-surgical home care',
      'Stroke & neuro recovery',
      "Alzheimer's & dementia",
      "Parkinson's support",
      'Bedridden management',
      'Cardiac monitoring partnerships',
      'CKD & diabetes routines',
      'Orthopaedic recovery',
      'Cancer comfort care',
      'COPD / respiratory support',
      'ICU discharge transitions',
      'NRI parent coordination',
    ],
    stories: [
      {
        quote:
          'The home care professional EzyHelpers had worked with diabetic-kidney patients before. In the eight months since placement, we have had zero hospital readmissions.',
        emphasisPhrase: 'zero hospital readmissions.',
        name: 'Kiran Reddy',
        location: 'Electronic City, Bangalore',
        initials: 'KR',
      },
      {
        quote:
          'The home care arrangement EzyHelpers set up has been a lifeline. The caregiver sends a detailed update every evening, handles all doctor appointments, and has built a genuine relationship with both our parents.',
        emphasisPhrase: 'a lifeline.',
        name: 'Arun Sharma',
        location: 'NRI family, Koramangala parents',
        initials: 'AS',
      },
      {
        quote:
          'EzyHelpers matched us with a home care professional who had worked specifically in post-cardiac recovery. She followed the cardiologist\'s instructions precisely, knew which symptoms to report immediately, and was a calm, steady presence throughout a frightening period.',
        emphasisPhrase: 'a calm, steady presence throughout a frightening period.',
        name: 'Sunita Narayanan',
        location: 'Indiranagar, Bangalore',
        initials: 'SN',
      },
    ],
    processIntro: {
      eyebrow: 'How it works',
      title: 'Four steps — every service line.',
      lede: 'Same backbone whether you need a nurse, caretaker, or attendant.',
    },
    processSteps: [
      { mark: 'i', title: 'Free consultation', body: 'We help you choose the right service if you’re unsure.' },
      { mark: 'ii', title: 'Shortlist 2–3 professionals', body: 'Matched to condition, schedule, and language.' },
      { mark: 'iii', title: 'Interview & confirm', body: 'Meet candidates before commitment.' },
      { mark: 'iv', title: 'Onboarding & support', body: 'Briefings, week-one follow-up, replacements if needed.' },
    ],
    finalCta: {
      titleBefore: 'Start with the right care',
      titleGradient: 'for your loved one.',
      lede: 'Tell us the situation — we typically respond within the hour on business days.',
      showPillarLink: false,
    },
  } satisfies CareClusterLandingConfig,
} as const

export type ClusterLandingKey = keyof typeof CLUSTER_LANDING_CONFIGS
